[[WCS]]
arch = "armv7l"
git-tree-sha1 = "1a0b6dfa42b1548446fcec824fe93ef0308c92ee"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "0f31606bf50ecccb0ee0d3d9468f762a4cc0e264d264d84287331859bb52e903"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.arm-linux-musleabihf.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "ae86888289f1d0d81222bc0bb571cbc937dc4b5f"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "3b1648a4cf1c4d221f9601b08ca6979eda2f889e4396c77159ea57e5415ded90"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "abe0287721ca51c51448534e845170c44236102d"
os = "macos"

    [[WCS.download]]
    sha256 = "d6223c267153789eeb62205dc779709ba6fe8f852946312aab3e00dfe62a1cc6"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.x86_64-apple-darwin14.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "6a49a77c38e3e6d526ece4bc4f2b5facaa322be1"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "fa1776aac792f7cb60b37daa296061c1b89f041a4bdfd041bfabd79913e8eb47"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "armv7l"
git-tree-sha1 = "e6c47fab89549248c6d5f5c9fc217c3a6c3d3959"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "b98e8c92c0eee52b2af5034a68c15353bb3e47887be21e0375ed413084487249"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.arm-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "87a95a8271adc407e53c39c087468b4a7c222972"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "aeb1cda6a06c8e6620749f7253494834b34d4ee2b76de27ad32f93ef5b651671"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "7a61af99a9cfe6a55f52a5f400393b202dd39571"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "5f0211edfbd0e440bd66cb223274f975cd8bd93e5962ed173752770432b745e2"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "4175d30242d97919049d8a5113bddf704128351c"
os = "windows"

    [[WCS.download]]
    sha256 = "51c6392b3e3b52794b4e071884f53c87463eb89c7a6e51561890ae83cae6f034"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.x86_64-w64-mingw32.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "f626434c855c98492fd8cce88edd07a2ba8d34e7"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "78058c0742e69dfb46352b7175e41fdb097e59384d2ad658e5ebcca6fac68271"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "a95c6d4c15c60bcde6fc3a7020cc9a606b70e626"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "6b216b366d53a8e163063ed1b7a9018100565d9eb414f4f5323e5779b9405f3f"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "22195379eeb8833416f5bb736ffe1b3b638f5b2f"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "024ca4ee23f23c8dcf6d8068b9c239d59145e3397f95ade1810de0dd758165dd"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "138cf00186ab00f823133b5bd97efda988062155"
os = "freebsd"

    [[WCS.download]]
    sha256 = "8552153a47057b85e84e21f21f5a334ba34a4a706a64f71fbc98c2fc903a1441"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "db93571af97bbbee002a6bef523c78edf9954706"
os = "windows"

    [[WCS.download]]
    sha256 = "47ec23d8ff3a3bb1f5fee97820fd3c94dbcb9248b497effcbec94ab2508a4ad8"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v6.4.0+1/WCS.v6.4.0.i686-w64-mingw32.tar.gz"
